### PR TITLE
[AutoFDO] Improve data structures for address mapping

### PR DESCRIPTION
**Pull request by DavidCallahan**
Summary: This rewrites one of the internal data structures to use a
    couple of std::map's instead of simple linked list with linear
    searches.

For some large profile inputs, this is almost 5 times faster.

### CODE REVIEW

**Comment by DavidCallahan** [comment]
I have been added to Facebook’s corporate CLA
—david

**Comment by danielcdh** [comment]
Thanks for the optimization!

These code comes from quipper: https://chromium.googlesource.com/chromiumos/platform/chromiumos-wide-profiling/

The original plan is that we sync to upstream periodically. But as recent change in upstream that adds dependency from quipper to protobuf, it becomes much harder to sync if we do not want protobuf as part of the toolchain.

As a result, the tool chain has not been synced with upstream for a while. I guess in the long run, we probably will just cherry-pick critical bug fixes from upstream and when new features in perf.data is added, we may need some significant rebase work.

That being said, it's fine to merge this optimization here. But in the long run, if you do not want to lose this optimization after we do major rebasing, it's a good idea to commit something similar to quipper upstream too.

Thanks,
Dehao

**Comment by danielcdh** [comment]
Sorry, the correct upstream link is:
https://chromium.googlesource.com/chromiumos/platform2/+/f1eed6c2806b4cfa4114f5ecbfb1e6582ce717c6/chromiumos-wide-profiling/

**Comment by DavidCallahan** [comment]
Hi Dehao, sorry for the nOOb question, but what do I do what that link?

**Comment by danielcdh** [comment]
It would be best if you can also contribute your patch to the upstream
projects there.

The link to git clone source there is in:

https://chromium.googlesource.com/chromiumos/platform2/

Dehao

**Pull request merged**
