### PR TITLE
minor generated file clean up

### PR DESCRIPTION
**Pull request by vapier**

### CODE REVIEW

**Comment by danielcdh** [comment]
I'm not very familiar with autoconf. But my normal workflow is:

#./configure
#make

As Diego is going to update the autoconf framework to integrate llvm bits into github, I'll defer to him to decide if we should remove these generated files.

**Comment by vapier** [comment]
typically people run `autoreconf -f -i`, or if the build requires a few more steps, they'll add an `./autogen.sh` script to do all the right things.  the trouble with checking in generated files is that not everyone has the same exact set of autotool packages or versions, so you end up getting a lot of noise/thrashing.

but Diego knows all of this, so i'm not worried :).

**Comment by dnovillo** [comment]
Yeah, I'll take care of this.  I'm now modifying the autoconf bits to add
support for LLVM headers and libraries that I need.  I'll do a cleanup pass
after I get this working.

Thanks and sorry it's taken so long to get around this!

**Comment by dnovillo** [comment]
Actually, we don't really want to remove all the autogenerated files.  I'd like to avoid forcing users to run autoconf first.  I'll leave a few of them around.

**Comment by vapier** [comment]
how do you sanely deal with updates ?  you can't really guarantee everyone has the same version when sending pull requests/patches.

keep in mind that just because the git repo is clean does not mean releases cannot have generated files.  standard open source behavior is not check in generated files like this to git, but include them in the release tarballs.  expecting people to run autotools in releases is unreasonable, but expecting people who are checking out the latest dev code from git to run autotools is perfectly reasonable.

**Comment by dnovillo** [comment]
On Tue, Mar 1, 2016 at 4:08 PM, Mike Frysinger <notifications@github.com>
wrote:

> how do you sanely deal with updates ? you can't really guarantee everyone
> has the same version when sending pull requests/patches.
>
> keep in mind that just because the git repo is clean does not mean
> releases cannot have generated files. standard open source behavior is not
> check in generated files like this to git, but include them in the release
> tarballs. expecting people to run autotools in releases is unreasonable,
> but expecting people who are checking out the latest dev code from git to
> run autotools is perfectly reasonable.
>

Yeah.  I never get used to projects that want to run autotools at head.
I'm more used to having some of the autogenerated stuff committed.  Let me
finish this up and think of a better balance.

In general, if someone is modifying an autoconf file, I'd rather have them
know and use the proper autotool version.  I don't want to rely on other
developers having to have auto-tools unless they're changing these files
(which don't really change all that often).

**Comment by vapier** [comment]
how are you defining "the proper autotool version" ?  the distro-specific version you happened to have installed on your system at any point in time ?  remember that diff distros have diff upgrade cycles, and they often patch autotools differently (doing backports of features or bug fixes).  so while you might be able to regenerate the same content everytime on e.g. Ubuntu Trusty, there's no guarantee at all that it'll work for any other distro or even version of Ubuntu.

if you want to require certain min versions, autotools already supports this: in configure.ac, you can use  ```AC_PREREQ([2.69])``` and ```AM_INIT_AUTOMAKE([1.14])```.  that's the standard in the open source world for making sure things work.

**Comment by dnovillo** [comment]
On Tue, Mar 1, 2016 at 4:53 PM, Mike Frysinger <notifications@github.com>
wrote:

> how are you defining "the proper autotool version" ?
>
You just anchor it with AC_PREREQ and friends.

**Comment by vapier** [comment]
unfortunately, as i described, that doesn't work for two reasons:

1. `AC_PREREQ` defines only a version *minimum*; see the [manual](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Versioning.html).  people are free to use a newer version.
2. that doesn't isolate you from distro-specific changes which happen all the time.  i don't just mean backports to fix tests, but patches that change the generated output.  these often cover the m4 inputs and source scripts.  i know for a fact i've seen Debian/Ubuntu/Fedora carry these changes, and i've added them myself to Gentoo.  i.e. even if we're both using autoconf-2.69, when i run `autoreconf -fi`, the generated `configure` script will not match.

**Comment by dnovillo** [comment]
On Tue, Mar 1, 2016 at 5:49 PM, Mike Frysinger <notifications@github.com>
wrote:

> unfortunately, as i described, that doesn't work for two reasons:
>
>    1. AC_PREREQ defines only a version *minimum*; see the manual
>    <https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Versioning.html>.
>    people are free to use a newer version.
>    2. that doesn't isolate you from distro-specific changes which happen
>    all the time. i don't just mean backports to fix tests, but patches that
>    change the generated output. these often cover the m4 inputs and source
>    scripts. i know for a fact i've seen Debian/Ubuntu/Fedora carry these
>    changes, and i've added them myself to Gentoo. i.e. even if we're both
>    using autoconf-2.69, when i run autoreconf -fi, the generated configure
>    script will not match.
>
>
Sure.  I understand all that and have been bitten by it many times.  This
is something we continuously deal with in projects like GCC.  This is one
of the reasons I dislike autoconf and brethren so much.

I'm just balancing the needs of the many vs the few here.  A change to the
autoconf bits is going to be pretty rare in this tool (I'm doing the first
one in 3+ years), but we have many users of HEAD that just want
'./configure && make'.  I really don't want to force them to have the
"correct" version of autoconf and such.

If someone needs to modify these AC files, then they'll need to take care
of having the proper setup.

**Comment by vapier** [comment]
i don't think the binutils/gdb/gcc setup is a good one to model after.  they have a lot of historical baggage (often they're years behind -- they still use autoconf-2.64 & automake-1.11 ... when they use automake at all).  in fact, i often have pain when trying to work on those projects precisely because of this -- most distros don't even ship the old versions anymore which means you have to download & build & install by hand.  even distros that still have those versions you end up having to do it by hand anyways since they've been patched.

i still don't think it's onerous to have *developers* who are using *development versions straight out of git* to run autotools.  if people are trying to use this stuff more frequently, then that's what proper releases are for.  also not an area where mimicing binutils/gdb/gcc is a good idea -- their release pace is glacial at best.

**Pull request merged**
