### PR TITLE
Sync AFDO/Propeller with internal and enable Arm SPE support

### PR DESCRIPTION
**Pull request by dhoekwater**
This change:
  1. Updates necessary dependencies
  2. Brings AutoFDO and Propeller core libraries up to date
  3. Adds library functionality for SPE-driven Propeller and AutoFDO profile generation
  4. Enables SPE-driven Propeller and AutoFDO profile generation in create_llvm_prof

### CODE REVIEW

**Comment by dhoekwater** [comment]
The only test that fails is the glog symbolize test when LLVM is disabled. This test is actually failing within [glog itself](github.com/google/glog/pull/860), so I'm going to say this one's not on us.

**Review by shenhanc78 — COMMENTED** [review]
Could you describe how you sync'ed internal source code up here? We used to use an internal tool to do this, but it is now obsolete.

**Comment by dhoekwater** [comment]
Since my end goal was to add SPE support for AFDO/Propeller to `create_llvm_prof` my process was:
1. By hand, copy over SPE changes to `create_llvm_prof.cc`
2. For each broken dependency, `cp` the `.h`, `.cc`, and _test.cc` file from internal source
3. For each copied file, use `sed` to replace include paths and internal resources with their equivalents in this repo. Manually fix other breakages (namespaces, macros).
4. Repeat steps 2 - 3 until `create_llvm_prof` builds and produces the same result as our internal version for SPE data.
5. Make sure all existing and new tests pass.
6. Read through the diff to make sure nothing looks out of the ordinary (grep for internal resources, include guards, etc).

All code I copied over has been reviewed internally and tested, so although this PR is much too large to be reasonably reviewed on its own, it is made up of dozens of much-smaller changes that have been reviewed internally.

**Comment by snehasish** [comment]
This PR does not build for me on a fresh checkout with LLVM. Here are the steps I took:


```
$ sudo apt install libunwind-dev libgflags-dev libssl-dev libelf-dev protobuf-compiler
$ git clone --recursive https://github.com/google/autofdo.git
$ cd autofdo
$ gh pr checkout 191
$ cmake -G Ninja -DWITH_LLVM=On -DCMAKE_BUILD_TYPE=Release -S . -B Build/

[... 8< ...]

-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so (found version "3.21.12") 
-- Configuring done (19.4s)
CMake Error at CMakeLists.txt:757 (add_library):
  Cannot find source file:

    third_party/perf_data_converter/src/quipper/arm_spe_decoder.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  CMakeLists.txt:801 (config_with_llvm)


CMake Error at CMakeLists.txt:757 (add_library):
  No SOURCES given to target: quipper_perf
Call Stack (most recent call first):
  CMakeLists.txt:801 (config_with_llvm)


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Maybe the perf_data_converter dependency which we pull in via the `--recursive` clone needs to be rebased to a commit which contains the spe file?

**Review by snehasish — CHANGES_REQUESTED** [review]
PTAL at the build issue on a fresh checkout I noted in https://github.com/google/autofdo/pull/191#issuecomment-2078005648

**Comment by dhoekwater** [comment]
It looks like that's using an older version of perf_data-converter. Since I updated the `third_party/abseil`, `third_party/googletest`, and `third_party/perf-data-converter` submodules, you'll need to check them out with `gh pr checkout --recurse-submodules 191`.

```
$ sudo apt install libunwind-dev libgflags-dev libssl-dev libelf-dev protobuf-compiler
$ git clone --recursive https://github.com/google/autofdo.git
$ cd autofdo
$ gh pr checkout --recurse-submodules 191
$ cmake -G Ninja -DWITH_LLVM=On -DCMAKE_BUILD_TYPE=Release -S . -B Build/
$ ninja -C Build
```

That seems to work for me.

**Comment by erozenfeld** [comment]
Looks like this PR undoes https://github.com/google/autofdo/pull/156. Any reason for that?

**Comment by dhoekwater** [comment]
> Looks like this PR undoes #156. Any reason for that?

Nope, it looks like #156 (as well as #148, #155, etc) were never patched internally. Before merging this PR, I'll go through and reapply any merged PRs that haven't been internally synced.

**Review by snehasish — CHANGES_REQUESTED** [review]
Thanks, with `--recurse-submodules` I was able to build the repository but some of the   tests are failing. Here is the output:

```
$ ninja test                                                                                                                                                                                                       [0/11725]
[0/1] Running tests...                                                                                                                                                                                
Test project /usr/local/google/home/snehasishk/working/autofdo/Build                                                                                                                                  
      Start  1: symbol_map_test                                                                                                                                                                       
 1/23 Test  #1: symbol_map_test ..........................................   Passed    0.01 sec                                                                                                       
      Start  2: llvm_profile_reader_test                                                                                                                                                              
 2/23 Test  #2: llvm_profile_reader_test .................................   Passed    0.01 sec                                                                                                       
      Start  3: llvm_profile_writer_test                                                                                                                                                              
 3/23 Test  #3: llvm_profile_writer_test .................................   Passed    0.15 sec                                                                                                       
      Start  4: instruction_map_test                                                                                                                                                                  
 4/23 Test  #4: instruction_map_test .....................................   Passed    0.07 sec                                                                                                       
      Start  5: profile_symbol_list_test                                                                                                                                                              
 5/23 Test  #5: profile_symbol_list_test .................................   Passed    0.01 sec                                                                                                       
      Start  6: sample_reader_test                                                                                                                                                                    
 6/23 Test  #6: sample_reader_test .......................................   Passed    0.41 sec                                                                                                       
      Start  7: addr2cu_test                                                                                                                                                                          
 7/23 Test  #7: addr2cu_test .............................................   Passed    0.02 sec                                                                                                       
      Start  8: branch_frequencies_autofdo_sample_test                                                                                                                                                
 8/23 Test  #8: branch_frequencies_autofdo_sample_test ...................   Passed    0.02 sec                                                                                                       
      Start  9: lbr_branch_aggregator_test                                                                                                                                                            
 9/23 Test  #9: lbr_branch_aggregator_test ...............................   Passed    0.01 sec                                                                                                       
      Start 10: llvm_propeller_binary_address_mapper_test                                                                                                                                             
10/23 Test #10: llvm_propeller_binary_address_mapper_test ................***Failed    0.02 sec                                                                                                       
      Start 11: llvm_propeller_cfg_test                                                                                                                                                               
11/23 Test #11: llvm_propeller_cfg_test ..................................   Passed    0.02 sec                                                                                                       
      Start 12: llvm_propeller_file_perf_data_provider_test                                               
12/23 Test #12: llvm_propeller_file_perf_data_provider_test ..............   Passed    0.02 sec                                                                                                                                        
      Start 13: llvm_propeller_perf_branch_frequencies_aggregator_test
13/23 Test #13: llvm_propeller_perf_branch_frequencies_aggregator_test ...***Failed    0.02 sec
      Start 14: llvm_propeller_perf_lbr_aggregator_test                                                            
14/23 Test #14: llvm_propeller_perf_lbr_aggregator_test ..................   Passed    0.04 sec
      Start 15: llvm_propeller_profile_computer_test                                               
15/23 Test #15: llvm_propeller_profile_computer_test .....................Subprocess aborted***Exception:   0.03 sec                                                                                                                                        
      Start 16: llvm_propeller_profile_generator_test                                                                         
16/23 Test #16: llvm_propeller_profile_generator_test ....................***Failed    0.08 sec
      Start 17: llvm_propeller_program_cfg_builder_test                                            
17/23 Test #17: llvm_propeller_program_cfg_builder_test ..................   Passed    0.01 sec
      Start 18: llvm_propeller_program_cfg_proto_builder_test                                      
18/23 Test #18: llvm_propeller_program_cfg_proto_builder_test ............***Failed    0.01 sec
      Start 19: llvm_propeller_program_cfg_test                                                    
19/23 Test #19: llvm_propeller_program_cfg_test ..........................   Passed    0.01 sec    
      Start 20: llvm_propeller_statistics_test                                                     
20/23 Test #20: llvm_propeller_statistics_test ...........................   Passed    0.01 sec                                                                                                       
      Start 21: perfdata_reader_test                                                               
21/23 Test #21: perfdata_reader_test .....................................***Failed    0.04 sec    
      Start 22: spe_sample_reader_test                                                             
22/23 Test #22: spe_sample_reader_test ...................................***Failed    0.01 sec    
      Start 23: llvm_propeller_code_layout_test                                                    
23/23 Test #23: llvm_propeller_code_layout_test ..........................   Passed    0.05 sec    
                                                                                                          
70% tests passed, 7 tests failed out of 23                                                         
                                                                                                                   
Total Test time (real) =   1.10 sec                                                                
                                                                                                                                                                                                                     
The following tests FAILED:                                                                        
         10 - llvm_propeller_binary_address_mapper_test (Failed)                                                              
         13 - llvm_propeller_perf_branch_frequencies_aggregator_test (Failed)                                                                                                                                        
         15 - llvm_propeller_profile_computer_test (Subprocess aborted)                                                                                                                                                                
         16 - llvm_propeller_profile_generator_test (Failed)                                                       
         18 - llvm_propeller_program_cfg_proto_builder_test (Failed)                                                          
         21 - perfdata_reader_test (Failed)                                                                                                                                                                                            
         22 - spe_sample_reader_test (Failed)            
Errors while running CTest                               
Output from these tests are in: /usr/local/google/home/snehasishk/working/autofdo/Build/Testing/Temporary/LastTest.log                                                                                                                                      
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.                                                
FAILED: CMakeFiles/test.util                                   
cd /usr/local/google/home/snehasishk/working/autofdo/Build && /usr/bin/ctest --force-new-ctest-process                                                                                                                                                      
ninja: build stopped: subcommand failed.      
```
Attached the detailed test output separately here: 
[LastTest.txt](https://github.com/google/autofdo/files/15137085/LastTest.txt)

I ran this on a virtual machine which does not have perf events enabled. Skimming through the log at least a few of the failures seem real unrelated to this. Can you take a look?

**Comment by dhoekwater** [comment]
Since some of the test data files (specifically `propeller_sample.perfdata`) are too big for GitHub, I used `git-lfs` to store them. I assumed it would work out of the box, but it seems like that's not the case; in that case, I'll replace the synced `propeller_sample.perfdata` file with a smaller one (I doubt we really need such a large perf capture to test Propeller functionality).

**Comment by dhoekwater** [comment]
@snehasish the tests are fixed now, and I removed all of the `git lfs` bits. The last step will be for me to go through to make sure this change doesn't overwrite any GitHub PRs (yet another task that will be made easier with tooling!).

**Comment by snehasish** [comment]
Thanks a lot for working through this! Let me know when it's ready for me to take another look.

**Comment by dhoekwater** [comment]
> Looks like this PR undoes https://github.com/google/autofdo/pull/156.

Fixed. It also undid #134, so I patched that in as well.
@snehasish, it should be good to go whenever you're ready!

**Review by snehasish — APPROVED** [review]
LGTM.

**Pull request merged**
